apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openhab2.fullname" . }}
  labels:
    {{- include "openhab2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openhab2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openhab2.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "openhab2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- toYaml .Values.env | nindent 10 }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          initialDelaySeconds: 600
          periodSeconds: 10
          httpGet:
            path: /
            port: http
        readinessProbe:
          initialDelaySeconds: 600
          periodSeconds: 10
          httpGet:
            path: /
            port: http

        volumeMounts:
          - mountPath: /etc/localtime
            name: localtime
            readOnly: true
          - mountPath: /etc/timezone
            name: timezone
            readOnly: true
          - mountPath: /openhab/conf
            name: storage
{{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}/conf
{{- else }}
            subPath: conf
{{- end }}
          - mountPath: /openhab/userdata
            name: storage
{{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}/userdata
{{- else }}
            subPath: userdata
{{- end }}
          - mountPath: /openhab/addons
            name: storage
{{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}/addons
{{- else }}
            subPath: addons
{{- end }}
          - mountPath: /openhab/.java
            name: storage
{{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}/.java
{{- else }}
            subPath: .java
{{- end }}
          {{- range .Values.volume.other }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: storage
{{- if and .Values.persistence.enabled (eq .Values.persistence.type "pvc") }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "openhab2.fullname" .) }}
{{- else if and .Values.persistence.enabled (eq .Values.persistence.type "hostPath") }}
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
{{- else }}
          emptyDir: {}
{{- end }}
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          hostPath:
            path: /etc/timezone
        {{- range .Values.volume.other }}
        - name: {{ .name }}
          {{- toYaml .mount | nindent 10 }}
        {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
