apiVersion: v1
kind: Service
metadata:
  name: {{ include "openhab2.fullname" . }}
  labels:
    {{- include "openhab2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.webdav.port }}
      targetPort: 8001
      protocol: TCP
      name: webdav
  selector:
    {{- include "openhab2.selectorLabels" . | nindent 4 }}
